spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    servlet:
      path: /api/v1
  main:
    allow-bean-definition-overriding: true

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

# Swagger OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# JWT Configuration
jwt:
  secret: sophiaHotelPaymentServiceSecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds
