name: sophia_hotel

services:
  payment-service:
    container_name: payment-service
    build:
      context: ../
      target: runtime
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - DATABASE_URL=jdbc:postgresql://dpg-d0e324odl3ps73ba0fsg-a.singapore-postgres.render.com/payment_postgres
      - DATABASE_USERNAME=payment_postgres_user
      - DATABASE_PASSWORD=uNUen5Vg8VPxL7vpKdPfQyLC0hTEK3WA
    networks:
      - sophia_hotel

volumes:
  postgres:

networks:
  sophia_hotel:
    driver: bridge